### ISSUE TITLE
Rumble for the XBOX controllers

### ISSUE THREAD

**Issue by travis615704** [Team2550/Robot-Code-Pre-2019#1]
WPILib now has rumble support for the XBOX controllers, and as a matter of principle, we must find a way to incorporate it into our program.
NOTE: This is Lance, but Travis left the laptop logged into his account, and I'm running short on time, so I'm just going to submit this as him.

**Comment by Gerdathlete** [comment]
I got you fam
Use setRumble(controller, [RumbleLeft or RumbleRight], rumbleAmount [0 to 1])
